package ch.epfl.tchu.gui;

import ch.epfl.tchu.SortedBag;
import ch.epfl.tchu.game.*;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ArrayBlockingQueue;

import static javafx.application.Platform.runLater;

/**
 * @author Alberto Centonze (327267)
 * Adapter to make GraphicalPlayer implement the interface Player
 */
public final class GraphicalPlayerAdapter implements Player {
    private GraphicalPlayer graphicalPlayer;
    // All the blocking queues used to exchange variables between javafx and the game thread
    private final ArrayBlockingQueue<SortedBag<Ticket>> ticketsQueue = new ArrayBlockingQueue<>(1);
    private final ArrayBlockingQueue<SortedBag<Card>> claimCardsQueue = new ArrayBlockingQueue<>(1);
    private final ArrayBlockingQueue<Integer> drawSlotQueue = new ArrayBlockingQueue<>(1);
    private final ArrayBlockingQueue<Route> routeQueue = new ArrayBlockingQueue<>(1);
    private final ArrayBlockingQueue<TurnKind> turnQueue = new ArrayBlockingQueue<>(1);


    /**
     * Initializes a new instance of GraphicalPlayer for the corresponding id
     * @param ownId : the id of the player
     * @param playerNames : the map containing the string representation of the players' names
     */
    @Override
    public void initPlayers(PlayerId ownId, Map<PlayerId, String> playerNames) {
        runLater(() -> graphicalPlayer = new GraphicalPlayer(ownId, playerNames));
    }

    /**
     * Sends the received information to the message panel in javafx
     * @param info : the information communicated (usually generated by Info)
     */
    @Override
    public void receiveInfo(String info) {
        runLater(() -> graphicalPlayer.receiveInfo(info));
    }


    /**
     * Updates the state of the game in the javafx window
     * @param newState : the new state
     * @param ownState : the previous state
     */
    @Override
    public void updateState(PublicGameState newState, PlayerState ownState) {
        runLater(() -> graphicalPlayer.setState(newState, ownState));
    }

    /**
     * Asks to the player which tickets he wants to keep at the beginning of the game
     * @param tickets : the tickets of the player
     */
    @Override
    public void setInitialTicketChoice(SortedBag<Ticket> tickets) {
        runLater(() -> graphicalPlayer.chooseTickets(tickets,
                ticketsQueue::add));
    }

    /**
     * Returns the tickets that were initially chosen via the javafx window
     * @return the sorted bag containing the kept tickets
     */
    @Override
    public SortedBag<Ticket> chooseInitialTickets() {
        return takeFromQueue(ticketsQueue);
    }

    /**
     * Waits for the player to make his move and then returns the corresponding TurnKind
     * @return the type of action the player wants to perform in this turn
     */
    @Override
    public TurnKind nextTurn() {
        runLater(() -> graphicalPlayer.startTurn(
                //ticket handler
                () -> {
                    turnQueue.add(TurnKind.DRAW_TICKETS);
                },
                // card handler
                slot -> {
                    drawSlotQueue.add(slot);
                    turnQueue.add(TurnKind.DRAW_CARDS);
                },
                // route handler
                (route, initialClaimCards) -> {
                    routeQueue.add(route);
                    claimCardsQueue.add(initialClaimCards);
                    turnQueue.add(TurnKind.CLAIM_ROUTE);
                }));
        return takeFromQueue(turnQueue);
    }

    /**
     * Waits for the player to choose some tickets from the modal window and then returns them
     * @param options : the tickets drawn
     * @return the selected tickets
     */
    @Override
    public SortedBag<Ticket> chooseTickets(SortedBag<Ticket> options) {
        runLater(() -> graphicalPlayer.chooseTickets(options,
                ticketsQueue::add));
        return takeFromQueue(ticketsQueue);
    }

    /**
     * Waits for the player to draw a card using the javafx window and then returns the selected slot
     * @return the integer corresponding to the chosen slot
     */
    @Override
    public int drawSlot() {
        if (drawSlotQueue.size() == 0){
            runLater(() -> graphicalPlayer.drawCard(
                    drawSlotQueue::add));
        }
        return takeFromQueue(drawSlotQueue);
    }

    /**
     * Returns the route that the player has claimed via the javafx window
     * @return the claimed route
     */
    @Override
    public Route claimedRoute() {
        return takeFromQueue(routeQueue);
    }

    /**
     * Returns the cards that the player selected via the javafx window to claim the route
     * @return the cards to claim the route
     */
    @Override
    public SortedBag<Card> initialClaimCards() {
        return takeFromQueue(claimCardsQueue);
    }

    /**
     * Waits for the user to choose the additional cards from the javafx window and then returns them
     * @param options : the card options from which to choose the additional cards
     * @return the additional cards chosen by the player
     */
    @Override
    public SortedBag<Card> chooseAdditionalCards(List<SortedBag<Card>> options) {
        runLater(() -> graphicalPlayer.chooseAdditionalCards(options,
                claimCardsQueue::add));
        return takeFromQueue(claimCardsQueue);
    }

    private <T> T takeFromQueue(ArrayBlockingQueue<T> queue){
        try{
            return queue.take();
        }catch (InterruptedException e){
            throw new Error(e);
        }
    }
}
